<script type="text/javascript">
//<![CDATA[
	<?php if (!Mage::helper('quickshop')->getConfig('enable')): ?>
	window.EM_QUICKSHOP_DISABLED = true;
	<?php endif; ?>
	
	if (typeof EM == 'undefined') EM = {};
	EM.QuickShop = {
		BASE_URL : '<?php echo $this->getUrl() ?>',
		QS_FRM_TYPE : <?php echo Mage::getStoreConfig('quickshop/general/size_type');?>,
		QS_FRM_WIDTH : <?php echo Mage::getStoreConfig('quickshop/general/frame_width');?>,
		QS_FRM_HEIGHT : <?php echo Mage::getStoreConfig('quickshop/general/frame_height');?>,
		QS_TEXT: '<?php echo $this->__('QUICK SHOP'); ?>',
		QS_BTN_WIDTH : 115,
		QS_BTN_HEIGHT : 30,
        QS_ITEM_CLASS : ".products-grid .product-item, .products-grid .item, .products-list .item, <?php echo Mage::getStoreConfig('quickshop/developer/item_class');?>",
        QS_A_CLASS : "<?php echo Mage::getStoreConfig('quickshop/developer/a_class');?>",
        QS_IMG_CLASS : "<?php echo Mage::getStoreConfig('quickshop/developer/img_class');?>",
		QS_OVERLAY_CLOSE : <?php echo (Mage::getStoreConfig('quickshop/general/overlay_close')==1)? 'true' : 'false'; ?>,		
	};

	if(EM.QuickShop.QS_FRM_TYPE == 0 ){
		EM.QuickShop.QS_FRM_WIDTH = EM.QuickShop.QS_FRM_WIDTH + "%";
		EM.QuickShop.QS_FRM_HEIGHT = EM.QuickShop.QS_FRM_HEIGHT + "%";
	}


//]]	
</script> 
