<?php 
    $storeId = Mage::app()->getStore()->getId();
	$posts = Mage::getModel('blog/post')->getCollection()
			->setStoreId($storeId)	
			->addAttributeToSelect('*')
			->addAttributeToFilter('status',1)
			->addAttributeToSort('created_at','DESC');
    //$thumnailWidth = 423;
	//$thumnailHeight = 270;
    $thumnailWidth = Mage::getStoreConfig('blog/info/thumbnail_width');
	$thumnailHeight = Mage::getStoreConfig('blog/info/thumbnail_height');
    $helper = Mage::helper('cms');
	$helperBlog = Mage::helper('blog'); 
    
?>
<?php if($posts->count() > 0):?>    
	<ul class="em-latest-news">
    <?php $i=1; foreach ($posts as $p): ?>
		<li class="em-latest-news-item col-sm-8">
			<div class="em-blog-item">
				<?php if($p->getImage()):?>
				<div class="em-blog-image">
					<a title="em-sample-title" href="<?php echo $p->getPostUrl();?>">
						<img alt="<?php echo $p->getTitle();?>" class="img-responsive img-banner-small em-img-lazy" alt="" src="<?php echo $this->getSkinUrl('images/loading.gif'); ?>" data-original="<?php echo $helperBlog->resizeImage($p->getImage(),$thumnailWidth,$thumnailHeight,"emblog/post",'thumbnail');?>"/>
					</a>
				</div>
				<?php endif;?>
				<div class="em-blog-content">
					<h5 class="em-blog-title"><a href="<?php echo $p->getPostUrl(false);?>"><?php echo $p->getTitle();?></a></h5>
					
					<a class="comment-post-link" href="<?php echo $p->getPostUrl(); ?>" ><?php echo $this->__('Comments')?></a>
					<?php
						$content = $p->getPostIntro();
						if (strlen($content) > 150)
						{
							$temp = substr($content, 0, 150);
							$plit = explode(" ", $temp);
							$temp = array_slice($plit, 0, count($plit) - 1);
							$content = implode(" ", $temp);
						}
					?>
					<p class="em-blog-des"><?php echo strip_tags($content)?>&hellip;</p>
					
					<div class="btn_readmore"><a href=""><?php echo $this->__('Read more &gt;')?></a></div>
				</div>
			</div>
		</li>
		<?php $i++;?>
		<?php if ($i==4) break;?>
    <?php endforeach; ?>
	</ul>
<?php else:?>
    <p class="note-msg"><?php echo $this->__('There are no posts matching the selection.')?></p>
<?php endif;?>